name: Verificação da classe DocumentMINHACLASSE

on:
  pull_request:
    branches: [ main, dev, test ]
  push:
    branches: [ main, dev, test ]

jobs:
  check-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Procurar termos na classe DocumentMINHACLASSE
        id: check_terms
        run: |
          FILE=$(grep -ril -include="*.java" "class DocumentMINHACLASSE" . || true)

          if [ -z "$FILE" ]; then
            echo "found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Arquivo encontrado: $FILE"

          if grep -q "um dois três" "$FILE"; then
            if grep -q "cada um no seu quadrado" "$FILE"; then
              echo "found=true" >> $GITHUB_OUTPUT
              echo "file=$FILE" >> $GITHUB_OUTPUT
              exit 1
            fi
          fi

          echo "found=false" >> $GITHUB_OUTPUT

      - name: Comentar no PR se houver problema
        if: failure() && steps.check_terms.outputs.found == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const file = process.env.FILE || "${{ steps.check_terms.outputs.file }}";
            const pr = context.payload.pull_request;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `❌ A classe **DocumentMINHACLASSE** contém **"um dois três"** e também **"cada um no seu quadrado"** no arquivo \`${file}\`.  
              
Por favor, remova essa combinação antes do merge.`
            });
