name: Verificação da classe DocumentMINHACLASSE

on:
  pull_request:
    branches: [ main, dev, test ]
  push:
    branches: [ main, dev, test ]

jobs:
  check-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Procurar termos na classe DocumentMINHACLASSE
        run: |
          # Procurar o arquivo contendo a classe DocumentMINHACLASSE
          FILE=$(grep -rl "class DocumentMINHACLASSE" . || true)

          if [ -z "$FILE" ]; then
            echo "Classe DocumentMINHACLASSE não encontrada. Ignorando."
            exit 1
          fi

          echo "Arquivo encontrado: $FILE"

          # Verificar se contém 'um dois três'
          if grep -q "um dois três" "$FILE"; then
            echo "Encontrado 'um dois três'. Agora verificando por 'cada um no seu quadrado'..."
            
            if grep -q "cada um no seu quadrado" "$FILE"; then
              echo "❌ Erro: Encontrado 'um dois três' E 'cada um no seu quadrado' na classe DocumentMINHACLASSE."
              exit 1
            else
              echo "✔ Encontrado 'um dois três', mas NÃO 'cada um no seu quadrado'. OK."
            fi
          else
            echo "✔ Não encontrado 'um dois três'. OK."
          fi
