name: Cleanup branches antigas

on:
  schedule:
    - cron: "16 23 * * *"  # roda todo domingo às 03:00 UTC
  workflow_dispatch:      # também pode rodar manualmente

jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Apagar branches inativas há mais de 365 dias
        uses: actions/github-script@v7
        with:
          script: |
            const daysOld = 365;
            const cutoff = new Date();
            cutoff.setDate(cutoff.getDate() - daysOld);

            const branches = await github.paginate(
              github.rest.repos.listBranches,
              { owner: context.repo.owner, repo: context.repo.repo, protected: false }
            );

            for (const branch of branches) {
              const branchName = branch.name;
              const refData = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: branch.commit.sha
              });
              const commitDate = new Date(refData.data.commit.author.date);

              if (commitDate < cutoff) {
                console.log(`🧹 Deletando branch ${branchName} (último commit: ${commitDate.toISOString()})`);
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${branchName}`
                });
              }
            }
